allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - astro@6.4.2
  - '@astrojs/markdown-satteri@0.3.1'
  - '@astrojs/vercel@11.0.0'
  - astro@7.0.0
overrides:
  '@tailwindcss/vite>vite': ^7.0.0
  '@vercel/routing-utils>path-to-regexp': ^6.3.0
  yaml: ^2.9.0
