allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAge: 0
overrides:
  '@vercel/routing-utils>path-to-regexp': ^6.3.0
  undici: '^8.10.0'
  yaml: '>=2.9.0'
  js-yaml: '^5.4.1'
  tar: '>=7.5.22'
